import test from 'node:test';import assert from 'node:assert/strict';
import {applyAssessmentUpdate as apply,emptyAssessment} from '../index.mjs';
const change={issueId:'',title:'Buyer',interpretation:'Founder reports the VP owns the budget.',whyChanged:'The answer names the buyer.',communication:'clarified',evidence:'reported',direction:'unchanged',sourceIds:['U1']};
const update=(changes=[change])=>({summary:'Buyer clarified; demand remains untested.',changes,nextQuestion:'What has the buyer committed to?',needsResearch:false});
const run=(u=update(),p=emptyAssessment(),s='turn-1')=>apply({previous:p,update:u,sources:[{id:'U1',kind:'statement'},{id:'M1',kind:'document'}],snapshotId:s});
test('clarification preserves attribution and source snapshot; later correction retains identity',()=>{const a=run();const b=run(update([{...change,issueId:a.issues[0].id,interpretation:'The buyer was corrected.',direction:'weakens'}]),a,'turn-2');assert.equal(b.issues[0].id,a.issues[0].id);assert.equal(b.changes[0].before.evidenceRefs[0].snapshotId,'turn-1');assert.equal(b.issues[0].evidenceRefs[0].snapshotId,'turn-2');assert.equal(a.revision,1);});
test('no change preserves unresolved issues',()=>{const a=run(),b=run(update([]),a,'turn-2');assert.deepEqual(b.issues,a.issues);assert.equal(b.changes.length,0);});
test('rejects invented citations, unknown IDs, duplicate changes, stale state and false corroboration',()=>{assert.throws(()=>run(update([{...change,sourceIds:['invented']}])));assert.throws(()=>run(update([{...change,evidence:'supported'}])));assert.throws(()=>run(update([{...change,issueId:'invented'}])));const a=run();const c={...change,issueId:a.issues[0].id};assert.throws(()=>run(update([c,c]),a));assert.throws(()=>apply({previous:a,baseRevision:0,update:update(),sources:[],snapshotId:'x'}));});
test('original documents allow qualified evidence assessment, not report-only verification',()=>{assert.equal(run(update([{...change,evidence:'supported',sourceIds:['M1']}])).issues[0].evidence,'supported');assert.throws(()=>apply({update:update([{...change,evidence:'supported'}]),sources:[{id:'U1',kind:'interpretation'}],snapshotId:'x'}));});
